"""Increase phone_number column size

Revision ID: b01be3fcfbff
Revises: 2abd8777f28d
Create Date: 2025-07-18 22:46:03.951334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b01be3fcfbff'
down_revision = '2abd8777f28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###
