"""empty message

Revision ID: b08dfbd6ef01
Revises: 
Create Date: 2025-07-18 01:34:38.313166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08dfbd6ef01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('price')
        batch_op.drop_column('appointment_type')

    # ### end Alembic commands ###
